package output

import (
	"fmt"
	"strings"

	"github.com/AtomicWasTaken/surge/internal/model"
)

// MarkdownOutput renders review results as GitHub-flavored markdown.
type MarkdownOutput struct {
	commentMarker string
}

// NewMarkdownOutput creates a new markdown output renderer.
func NewMarkdownOutput(commentMarker string) *MarkdownOutput {
	return &MarkdownOutput{
		commentMarker: commentMarker,
	}
}

// RenderSummary renders the full review summary as a markdown comment.
func (m *MarkdownOutput) RenderSummary(result *model.ReviewResult) string {
	var sb strings.Builder

	sb.WriteString("<!-- ")
	sb.WriteString(m.commentMarker)
	sb.WriteString(" -->\n")
	sb.WriteString("<!-- ")
	sb.WriteString(m.commentMarker)
	sb.WriteString("_SUMMARY -->\n")
	sb.WriteString("# AI Code Review by surge\n\n")

	// Header stats
	sb.WriteString("| Files | Findings | Vibe Score | Approve |\n")
	sb.WriteString("|-------|----------|------------|--------|\n")

	findingCount := len(result.Findings)
	approveStr := "❌ Request Changes"
	if result.Approve {
		approveStr = "✅ Approve"
	}

	sb.WriteString(fmt.Sprintf("| %d | %d | %d/10 | %s |\n\n",
		result.Stats.FilesReviewed, findingCount, result.VibeCheck.Score, approveStr))

	// Separator
	sb.WriteString("---\n\n")

	// Executive Summary
	sb.WriteString("## Executive Summary\n\n")
	sb.WriteString("<details>\n")
	sb.WriteString("<summary>Click to expand...</summary>\n\n")
	sb.WriteString(result.Summary)
	sb.WriteString("\n\n</details>\n\n")

	// Files Overview
	if len(result.FilesOverview) > 0 {
		sb.WriteString("## Files Changed Overview\n\n")
		sb.WriteString("| File | Changes | Risk |\n")
		sb.WriteString("|------|---------|------|\n")
		for _, f := range result.FilesOverview {
			risk := riskEmoji(f.Risk) + " " + strings.ToUpper(f.Risk)
			sb.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", f.Path, f.Changes, risk))
		}
		sb.WriteString("\n")
	}

	// Findings by Severity
	if len(result.Findings) > 0 {
		bySeverity := groupBySeverity(result.Findings)
		for _, sev := range []model.Severity{model.SeverityCritical, model.SeverityHigh, model.SeverityMedium, model.SeverityLow, model.SeverityInfo} {
			findings := bySeverity[sev]
			if len(findings) == 0 {
				continue
			}
			emoji := severityEmoji(sev)
			sb.WriteString(fmt.Sprintf("### %s %s (%d)\n\n", emoji, severityLabel(sev), len(findings)))
			sb.WriteString("<details>\n")
			sb.WriteString("<summary>Click to expand...</summary>\n\n")

			sb.WriteString("| File | Line | Title | Category |\n")
			sb.WriteString("|------|------|-------|----------|\n")
			for _, f := range findings {
				line := "-"
				if f.Line > 0 {
					line = fmt.Sprintf("%d", f.Line)
				}
				sb.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n",
					f.File, line, f.Title, f.Category))
				sb.WriteString("\n")
				sb.WriteString(fmt.Sprintf("**%s**\n\n", f.Title))
				sb.WriteString(f.Body)
				sb.WriteString("\n\n---\n\n")
			}

			sb.WriteString("</details>\n\n")
		}
	}

	// Vibe Check
	sb.WriteString("## Vibe Check\n\n")
	sb.WriteString("<details>\n")
	sb.WriteString("<summary>")
	sb.WriteString(fmt.Sprintf("Score: %d/10", result.VibeCheck.Score))
	sb.WriteString("</summary>\n\n")
	sb.WriteString("**Score: ")
	sb.WriteString(fmt.Sprintf("%d/10", result.VibeCheck.Score))
	sb.WriteString("** -- ")
	sb.WriteString(result.VibeCheck.Verdict)
	sb.WriteString("\n\n")
	if len(result.VibeCheck.Flags) > 0 {
		sb.WriteString("Flags:\n")
		for _, flag := range result.VibeCheck.Flags {
			sb.WriteString(fmt.Sprintf("- `%s`\n", flag))
		}
		sb.WriteString("\n")
	}
	sb.WriteString("</details>\n\n")

	// Recommendations
	if len(result.Recommendations) > 0 {
		sb.WriteString("## Recommendations\n\n")
		sb.WriteString("<details>\n")
		sb.WriteString("<summary>Click to expand...</summary>\n\n")
		for i, rec := range result.Recommendations {
			sb.WriteString(fmt.Sprintf("%d. %s\n", i+1, rec))
		}
		sb.WriteString("\n</details>\n\n")
	}

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by [surge](https://github.com/AtomicWasTaken/surge) -- AI-powered PR reviews.*\n")

	return sb.String()
}

func severityEmoji(s model.Severity) string {
	switch s {
	case model.SeverityCritical:
		return "🔴"
	case model.SeverityHigh:
		return "🟠"
	case model.SeverityMedium:
		return "🟡"
	case model.SeverityLow:
		return "🔵"
	default:
		return "⚪"
	}
}

func riskEmoji(r string) string {
	switch r {
	case "high":
		return "🔴"
	case "medium":
		return "🟡"
	default:
		return "🟢"
	}
}

func severityLabel(s model.Severity) string {
	switch s {
	case model.SeverityCritical:
		return "CRITICAL"
	case model.SeverityHigh:
		return "HIGH"
	case model.SeverityMedium:
		return "MEDIUM"
	case model.SeverityLow:
		return "LOW"
	default:
		return "INFO"
	}
}

func groupBySeverity(findings []model.Finding) map[model.Severity][]model.Finding {
	result := make(map[model.Severity][]model.Finding)
	for _, f := range findings {
		result[f.Severity] = append(result[f.Severity], f)
	}
	return result
}
